#Name Of the Workflow/Pipeline
name: "Hello World Workflow"

# Trigger the Workflow
on:
    #Event to trigger the pipeline
    push:
        branches:
            - master
            - production


jobs:
    hellow_world:
        runs-on: ubuntu-latest
        steps:
            - name: "Print Hello World"
              run: echo "Hello World"

            - name: "Print Current Date"
              run: date  